jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            entities:
                namespace_prefix: "App"
                path: "%kernel.root_dir%/../config/serializer"
