App\Entity\User:
    exclusion_policy: ALL
    properties:
       id:
           expose: true
       name:
           expose: true
       surname:
           expose: true
       email:
           expose: true
