nelmio_api_doc:
    documentation:
        info:
            title: Social network api
            description: Social network aplication (Restful Api)
            version: 1.0.0
    routes:
        path_patterns:
            - ^/api(?!/doc)
